services:

  # ── Web service (Django) ────────────────────────────────────────────────────
  web:
    build: .
    ports:
      - "3333:3333" # Forçamos a porta 3333 que você está usando
    volumes:
      - ./src:/app/src
      - venv_data:/app/.venv
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  # ── MySQL service ───────────────────────────────────────────────────────
  mysql:
    image: mysql:8.0 # Usamos a imagem oficial direta para evitar erros de build
    container_name: mysql_db
    # Removi o "profiles" para o banco ligar SEMPRE que você der up
    environment:
      MYSQL_DATABASE: suppa
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # O VOLUME ESTÁ AQUI (Seus dados ficam salvos aqui)
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot --silent"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 20s

volumes:
  mysql_data: # Isso cria um "disco rígido" virtual que o Docker não apaga no down
  venv_data: