# Generated by Django 5.2.13 on 2026-05-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lote',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
