# Generated by Django 5.2.14 on 2026-05-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME_PRODUTO', models.CharField(max_length=255)),
                ('COD_BARRAS', models.CharField(max_length=100, unique=True)),
                ('MARGEM_PROMO', models.IntegerField(default=30)),
                ('CATEGORIA', models.CharField(blank=True, max_length=100, null=True)),
                ('SUBCATEGORIA', models.CharField(blank=True, max_length=100, null=True)),
                ('FOTO_PRODUTO', models.CharField(blank=True, max_length=255, null=True)),
                ('QTD_ESTOQUE', models.IntegerField(default=0)),
                ('UNIDADE_MEDIDA', models.CharField(default='UN', max_length=20)),
            ],
            options={
                'db_table': 'produtos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='HealthCheck',
        ),
    ]
